# Generated by Django 6.0.2 on 2026-02-14 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='chapters_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='guid',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='episode',
            name='remote_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='transcript_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='episode',
            name='transcript_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='podcast',
            name='custom_rss_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='funding_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='last_ingested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='remote_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts', to=settings.AUTH_USER_MODEL),
        ),
    ]
