# Generated by Django 6.0.2 on 2026-02-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_episode_chapters_url_episode_guid_episode_remote_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='remote_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='remote_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
