# Generated by Django 6.0.2 on 2026-02-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_episode_is_explicit_alter_episode_remote_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='transcript_content',
            field=models.TextField(blank=True, help_text='AI-generated transcript content'),
        ),
    ]
