# Generated by Django 6.0.2 on 2026-02-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_episode_transcript_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('role', models.CharField(default='Host', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='episodes', to='content.person'),
        ),
    ]
