# Generated by Django 6.0.2 on 2026-02-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_person_episode_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated concise summary'),
        ),
    ]
