# Generated by Django 6.0.2 on 2026-02-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_episode_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='plays',
            field=models.IntegerField(default=0, help_text='Total number of plays'),
        ),
    ]
