# Generated by Django 6.0.2 on 2026-02-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
