# Generated by Django 6.0.2 on 2026-02-15 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_episode_chapters_url_episode_guid_episode_remote_id_and_more'),
        ('sync', '0002_offlineevent_payload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.IntegerField(help_text='Total verified seconds listened in this session')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('processed_for_earnings', models.BooleanField(default=False)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
