"""
Django settings for podvault_api project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')





# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c9asdyoqrk4h*^mylh!1$new#m!b#+r$h#!!og&en#v+b@^*0('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Add React build directory to static files
REACT_BUILD_DIR = BASE_DIR / "static" / "react_build"
if REACT_BUILD_DIR.exists():
    STATICFILES_DIRS = [REACT_BUILD_DIR]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_celery_results',
    'corsheaders',
    'channels',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Server-side token invalidation on logout
    
    # Local Apps
    'users',
    'content',
    'ingest',
    'sync',
    'creator',
    'clubs',
    'payouts',
    'podcasts',  # Multi-provider podcast integration layer
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'podvault_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [REACT_BUILD_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'podvault_api.wsgi.application'
ASGI_APPLICATION = 'podvault_api.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise configuration
# Whitenoise configuration
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if os.getenv('BUNNY_STORAGE_ZONE_NAME'):
    STORAGES["default"]["BACKEND"] = "podvault_api.storage_backends.BunnyStorage"





# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else [
    'https://mc-7f8atnj8om.bunny.run',
    'http://localhost:5173',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}


# Spotify API Configuration
SPOTIFY_CLIENT_ID = os.getenv('SPOTIFY_CLIENT_ID', '')
SPOTIFY_CLIENT_SECRET = os.getenv('SPOTIFY_CLIENT_SECRET', '')

# Podcast Index & AI Configuration
PODCAST_INDEX_KEY = os.getenv('PODCAST_INDEX_KEY', '')
PODCAST_INDEX_SECRET = os.getenv('PODCAST_INDEX_SECRET', '')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# ---------------------------------------------------------------------------
# Podcast Provider Integration
# ---------------------------------------------------------------------------

# Redis Cache-Aside for podcast search results and hydrated detail objects.
# Uses DB 1 so it is isolated from Celery's broker (DB 0).
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # Don't raise on Redis connection errors — fall through to the API
            "IGNORE_EXCEPTIONS": True,
        },
        "KEY_PREFIX": "podvault",
    }
}

# TTL for cached podcast search / detail results (seconds).  Default: 24 h.
PODCAST_CACHE_TTL  = int(os.getenv("PODCAST_CACHE_TTL",  86400))  # 24 h — main Redis TTL
PODCAST_FRESH_TTL  = int(os.getenv("PODCAST_FRESH_TTL",  3600))   #  1 h — SWR sentinel TTL

# Taddy GraphQL API
TADDY_API_KEY  = os.getenv("TADDY_API_KEY", "")
TADDY_USER_ID  = os.getenv("TADDY_USER_ID", "")

# Podchaser API — credential pairs for OAuth 2.0 Client Credentials + automatic rotation.
# Format: comma-separated key:secret pairs.
# Example: PODCHASER_CREDENTIALS=key1:secret1,key2:secret2
# The provider exchanges each pair for a Bearer token (valid 1 year) cached in Redis.
PODCHASER_CREDENTIALS = os.getenv("PODCHASER_CREDENTIALS", "")
SPOTIFY_REDIRECT_URI = os.getenv('SPOTIFY_REDIRECT_URI', 'http://localhost:8000/api/ingest/spotify/callback')

# Bunny.net Storage Configuration
BUNNY_STORAGE_ZONE_NAME = os.getenv('BUNNY_STORAGE_ZONE_NAME')
BUNNY_STORAGE_PASSWORD = os.getenv('BUNNY_STORAGE_PASSWORD')
BUNNY_PULL_ZONE_URL = os.getenv('BUNNY_PULL_ZONE_URL')
BUNNY_STORAGE_REGION = os.getenv('BUNNY_STORAGE_REGION', 'de')

# Rumble Integration Configuration
RUMBLE_API_KEY = os.getenv('RUMBLE_API_KEY')
RUMBLE_S3_ENDPOINT = os.getenv('RUMBLE_S3_ENDPOINT', 'https://s3.rumble.com')
RUMBLE_ACCESS_KEY_ID = os.getenv('RUMBLE_ACCESS_KEY_ID')
RUMBLE_SECRET_ACCESS_KEY = os.getenv('RUMBLE_SECRET_ACCESS_KEY')
RUMBLE_MASTER_BUCKET = os.getenv('RUMBLE_MASTER_BUCKET', 'podvault-masters')





# Ingestion API Keys
MEDIASTACK_API_KEY = os.getenv('MEDIASTACK_API_KEY', '')
NPR_API_KEY = os.getenv('NPR_API_KEY', '')
